//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WebApplication2.ConsultarVuelos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultarVuelosPortBinding", Namespace="http://servicio/")]
    public partial class ConsultarVuelos : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VuelosIdaYVueltaOperationCompleted;
        
        private System.Threading.SendOrPostCallback pruebaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegistrarReservaOperationCompleted;
        
        private System.Threading.SendOrPostCallback VuelosIdaYVueltaCantidadOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConsultarVuelos() {
            this.Url = global::WebApplication2.Properties.Settings.Default.WebApplication2_ConsultarVuelos_ConsultarVuelos;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VuelosIdaYVueltaCompletedEventHandler VuelosIdaYVueltaCompleted;
        
        /// <remarks/>
        public event pruebaCompletedEventHandler pruebaCompleted;
        
        /// <remarks/>
        public event RegistrarReservaCompletedEventHandler RegistrarReservaCompleted;
        
        /// <remarks/>
        public event VuelosIdaYVueltaCantidadCompletedEventHandler VuelosIdaYVueltaCantidadCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicio/", ResponseNamespace="http://servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public vuelo[] VuelosIdaYVuelta([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string origen, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string destino, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime fechaSalida, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool fechaSalidaSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] System.DateTime fechaRegreso, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool fechaRegresoSpecified, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int nroPasajeros, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool nroPasajerosSpecified) {
            object[] results = this.Invoke("VuelosIdaYVuelta", new object[] {
                        origen,
                        destino,
                        fechaSalida,
                        fechaSalidaSpecified,
                        fechaRegreso,
                        fechaRegresoSpecified,
                        nroPasajeros,
                        nroPasajerosSpecified});
            return ((vuelo[])(results[0]));
        }
        
        /// <remarks/>
        public void VuelosIdaYVueltaAsync(string origen, string destino, System.DateTime fechaSalida, bool fechaSalidaSpecified, System.DateTime fechaRegreso, bool fechaRegresoSpecified, int nroPasajeros, bool nroPasajerosSpecified) {
            this.VuelosIdaYVueltaAsync(origen, destino, fechaSalida, fechaSalidaSpecified, fechaRegreso, fechaRegresoSpecified, nroPasajeros, nroPasajerosSpecified, null);
        }
        
        /// <remarks/>
        public void VuelosIdaYVueltaAsync(string origen, string destino, System.DateTime fechaSalida, bool fechaSalidaSpecified, System.DateTime fechaRegreso, bool fechaRegresoSpecified, int nroPasajeros, bool nroPasajerosSpecified, object userState) {
            if ((this.VuelosIdaYVueltaOperationCompleted == null)) {
                this.VuelosIdaYVueltaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVuelosIdaYVueltaOperationCompleted);
            }
            this.InvokeAsync("VuelosIdaYVuelta", new object[] {
                        origen,
                        destino,
                        fechaSalida,
                        fechaSalidaSpecified,
                        fechaRegreso,
                        fechaRegresoSpecified,
                        nroPasajeros,
                        nroPasajerosSpecified}, this.VuelosIdaYVueltaOperationCompleted, userState);
        }
        
        private void OnVuelosIdaYVueltaOperationCompleted(object arg) {
            if ((this.VuelosIdaYVueltaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VuelosIdaYVueltaCompleted(this, new VuelosIdaYVueltaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicio/", ResponseNamespace="http://servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string prueba([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string origen) {
            object[] results = this.Invoke("prueba", new object[] {
                        origen});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void pruebaAsync(string origen) {
            this.pruebaAsync(origen, null);
        }
        
        /// <remarks/>
        public void pruebaAsync(string origen, object userState) {
            if ((this.pruebaOperationCompleted == null)) {
                this.pruebaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpruebaOperationCompleted);
            }
            this.InvokeAsync("prueba", new object[] {
                        origen}, this.pruebaOperationCompleted, userState);
        }
        
        private void OnpruebaOperationCompleted(object arg) {
            if ((this.pruebaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.pruebaCompleted(this, new pruebaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicio/", ResponseNamespace="http://servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public mensaje[] RegistrarReserva([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string agencia, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string vuelo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string clase, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string dni, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int nroPasajes, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool nroPasajesSpecified) {
            object[] results = this.Invoke("RegistrarReserva", new object[] {
                        agencia,
                        vuelo,
                        clase,
                        dni,
                        nroPasajes,
                        nroPasajesSpecified});
            return ((mensaje[])(results[0]));
        }
        
        /// <remarks/>
        public void RegistrarReservaAsync(string agencia, string vuelo, string clase, string dni, int nroPasajes, bool nroPasajesSpecified) {
            this.RegistrarReservaAsync(agencia, vuelo, clase, dni, nroPasajes, nroPasajesSpecified, null);
        }
        
        /// <remarks/>
        public void RegistrarReservaAsync(string agencia, string vuelo, string clase, string dni, int nroPasajes, bool nroPasajesSpecified, object userState) {
            if ((this.RegistrarReservaOperationCompleted == null)) {
                this.RegistrarReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegistrarReservaOperationCompleted);
            }
            this.InvokeAsync("RegistrarReserva", new object[] {
                        agencia,
                        vuelo,
                        clase,
                        dni,
                        nroPasajes,
                        nroPasajesSpecified}, this.RegistrarReservaOperationCompleted, userState);
        }
        
        private void OnRegistrarReservaOperationCompleted(object arg) {
            if ((this.RegistrarReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegistrarReservaCompleted(this, new RegistrarReservaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://servicio/", ResponseNamespace="http://servicio/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VuelosIdaYVueltaCantidad([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string origen, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string destino, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fechaSalida, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fechaRegreso, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int nroPasajeros, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool nroPasajerosSpecified) {
            object[] results = this.Invoke("VuelosIdaYVueltaCantidad", new object[] {
                        origen,
                        destino,
                        fechaSalida,
                        fechaRegreso,
                        nroPasajeros,
                        nroPasajerosSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void VuelosIdaYVueltaCantidadAsync(string origen, string destino, string fechaSalida, string fechaRegreso, int nroPasajeros, bool nroPasajerosSpecified) {
            this.VuelosIdaYVueltaCantidadAsync(origen, destino, fechaSalida, fechaRegreso, nroPasajeros, nroPasajerosSpecified, null);
        }
        
        /// <remarks/>
        public void VuelosIdaYVueltaCantidadAsync(string origen, string destino, string fechaSalida, string fechaRegreso, int nroPasajeros, bool nroPasajerosSpecified, object userState) {
            if ((this.VuelosIdaYVueltaCantidadOperationCompleted == null)) {
                this.VuelosIdaYVueltaCantidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVuelosIdaYVueltaCantidadOperationCompleted);
            }
            this.InvokeAsync("VuelosIdaYVueltaCantidad", new object[] {
                        origen,
                        destino,
                        fechaSalida,
                        fechaRegreso,
                        nroPasajeros,
                        nroPasajerosSpecified}, this.VuelosIdaYVueltaCantidadOperationCompleted, userState);
        }
        
        private void OnVuelosIdaYVueltaCantidadOperationCompleted(object arg) {
            if ((this.VuelosIdaYVueltaCantidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VuelosIdaYVueltaCantidadCompleted(this, new VuelosIdaYVueltaCantidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicio/")]
    public partial class vuelo {
        
        private string aereolinaField;
        
        private int cantidadAsientosField;
        
        private bool cantidadAsientosFieldSpecified;
        
        private string claseField;
        
        private string destinoField;
        
        private System.DateTime fechaOrigenField;
        
        private bool fechaOrigenFieldSpecified;
        
        private string nombreAreolineaField;
        
        private string origenField;
        
        private double precioField;
        
        private bool precioFieldSpecified;
        
        private string tipoField;
        
        private string vuelo1Field;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string aereolina {
            get {
                return this.aereolinaField;
            }
            set {
                this.aereolinaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cantidadAsientos {
            get {
                return this.cantidadAsientosField;
            }
            set {
                this.cantidadAsientosField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadAsientosSpecified {
            get {
                return this.cantidadAsientosFieldSpecified;
            }
            set {
                this.cantidadAsientosFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clase {
            get {
                return this.claseField;
            }
            set {
                this.claseField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaOrigen {
            get {
                return this.fechaOrigenField;
            }
            set {
                this.fechaOrigenField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaOrigenSpecified {
            get {
                return this.fechaOrigenFieldSpecified;
            }
            set {
                this.fechaOrigenFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreAreolinea {
            get {
                return this.nombreAreolineaField;
            }
            set {
                this.nombreAreolineaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool precioSpecified {
            get {
                return this.precioFieldSpecified;
            }
            set {
                this.precioFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("vuelo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vuelo1 {
            get {
                return this.vuelo1Field;
            }
            set {
                this.vuelo1Field = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicio/")]
    public partial class mensaje {
        
        private string mensaje1Field;
        
        private string tipoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("mensaje", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensaje1 {
            get {
                return this.mensaje1Field;
            }
            set {
                this.mensaje1Field = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void VuelosIdaYVueltaCompletedEventHandler(object sender, VuelosIdaYVueltaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VuelosIdaYVueltaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VuelosIdaYVueltaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public vuelo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((vuelo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void pruebaCompletedEventHandler(object sender, pruebaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pruebaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal pruebaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void RegistrarReservaCompletedEventHandler(object sender, RegistrarReservaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegistrarReservaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegistrarReservaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public mensaje[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((mensaje[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void VuelosIdaYVueltaCantidadCompletedEventHandler(object sender, VuelosIdaYVueltaCantidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VuelosIdaYVueltaCantidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VuelosIdaYVueltaCantidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591