//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProyecto.ServicioHoteles {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebProyecto.ServicioHoteles.Hotel_cuarto[] cuartosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int departamanetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int provinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebProyecto.ServicioHoteles.Hotel_cuarto[] cuartos {
            get {
                return this.cuartosField;
            }
            set {
                if ((object.ReferenceEquals(this.cuartosField, value) != true)) {
                    this.cuartosField = value;
                    this.RaisePropertyChanged("cuartos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int departamaneto {
            get {
                return this.departamanetoField;
            }
            set {
                if ((this.departamanetoField.Equals(value) != true)) {
                    this.departamanetoField = value;
                    this.RaisePropertyChanged("departamaneto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int distrito {
            get {
                return this.distritoField;
            }
            set {
                if ((this.distritoField.Equals(value) != true)) {
                    this.distritoField = value;
                    this.RaisePropertyChanged("distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int provincia {
            get {
                return this.provinciaField;
            }
            set {
                if ((this.provinciaField.Equals(value) != true)) {
                    this.provinciaField = value;
                    this.RaisePropertyChanged("provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel_cuarto", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Hotel_cuarto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int capacidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double costo_nocheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int capacidad {
            get {
                return this.capacidadField;
            }
            set {
                if ((this.capacidadField.Equals(value) != true)) {
                    this.capacidadField = value;
                    this.RaisePropertyChanged("capacidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double costo_noche {
            get {
                return this.costo_nocheField;
            }
            set {
                if ((this.costo_nocheField.Equals(value) != true)) {
                    this.costo_nocheField = value;
                    this.RaisePropertyChanged("costo_noche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numero {
            get {
                return this.numeroField;
            }
            set {
                if ((this.numeroField.Equals(value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel_reserva", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Hotel_reserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cliente_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cuarto_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_finField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fecha_inicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string hotel_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int reserva_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string reserva_estadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cliente_ID {
            get {
                return this.cliente_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.cliente_IDField, value) != true)) {
                    this.cliente_IDField = value;
                    this.RaisePropertyChanged("cliente_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuarto_ID {
            get {
                return this.cuarto_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.cuarto_IDField, value) != true)) {
                    this.cuarto_IDField = value;
                    this.RaisePropertyChanged("cuarto_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_fin {
            get {
                return this.fecha_finField;
            }
            set {
                if ((this.fecha_finField.Equals(value) != true)) {
                    this.fecha_finField = value;
                    this.RaisePropertyChanged("fecha_fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha_inicio {
            get {
                return this.fecha_inicioField;
            }
            set {
                if ((this.fecha_inicioField.Equals(value) != true)) {
                    this.fecha_inicioField = value;
                    this.RaisePropertyChanged("fecha_inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string hotel_ID {
            get {
                return this.hotel_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.hotel_IDField, value) != true)) {
                    this.hotel_IDField = value;
                    this.RaisePropertyChanged("hotel_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int reserva_ID {
            get {
                return this.reserva_IDField;
            }
            set {
                if ((this.reserva_IDField.Equals(value) != true)) {
                    this.reserva_IDField = value;
                    this.RaisePropertyChanged("reserva_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reserva_estado {
            get {
                return this.reserva_estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.reserva_estadoField, value) != true)) {
                    this.reserva_estadoField = value;
                    this.RaisePropertyChanged("reserva_estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Destino", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Destino : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDepartamanetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdDistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreDestinoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDepartamaneto {
            get {
                return this.IdDepartamanetoField;
            }
            set {
                if ((this.IdDepartamanetoField.Equals(value) != true)) {
                    this.IdDepartamanetoField = value;
                    this.RaisePropertyChanged("IdDepartamaneto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdDistrito {
            get {
                return this.IdDistritoField;
            }
            set {
                if ((this.IdDistritoField.Equals(value) != true)) {
                    this.IdDistritoField = value;
                    this.RaisePropertyChanged("IdDistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProvincia {
            get {
                return this.IdProvinciaField;
            }
            set {
                if ((this.IdProvinciaField.Equals(value) != true)) {
                    this.IdProvinciaField = value;
                    this.RaisePropertyChanged("IdProvincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDestino {
            get {
                return this.NombreDestinoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreDestinoField, value) != true)) {
                    this.NombreDestinoField = value;
                    this.RaisePropertyChanged("NombreDestino");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioHoteles.IHoteles")]
    public interface IHoteles {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/listarTodosHoteles", ReplyAction="http://tempuri.org/IHoteles/listarTodosHotelesResponse")]
        WebProyecto.ServicioHoteles.Hotel[] listarTodosHoteles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/listarTodosHoteles", ReplyAction="http://tempuri.org/IHoteles/listarTodosHotelesResponse")]
        System.Threading.Tasks.Task<WebProyecto.ServicioHoteles.Hotel[]> listarTodosHotelesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/listarHotelesxHorarios", ReplyAction="http://tempuri.org/IHoteles/listarHotelesxHorariosResponse")]
        WebProyecto.ServicioHoteles.Hotel[] listarHotelesxHorarios(int dept, int prov, int dist, System.DateTime fecha_ini, System.DateTime fecha_fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/listarHotelesxHorarios", ReplyAction="http://tempuri.org/IHoteles/listarHotelesxHorariosResponse")]
        System.Threading.Tasks.Task<WebProyecto.ServicioHoteles.Hotel[]> listarHotelesxHorariosAsync(int dept, int prov, int dist, System.DateTime fecha_ini, System.DateTime fecha_fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/listarCuartosPorHotel", ReplyAction="http://tempuri.org/IHoteles/listarCuartosPorHotelResponse")]
        WebProyecto.ServicioHoteles.Hotel_cuarto[] listarCuartosPorHotel(string cod_hotel, System.DateTime fecha_ini, System.DateTime fecha_fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/listarCuartosPorHotel", ReplyAction="http://tempuri.org/IHoteles/listarCuartosPorHotelResponse")]
        System.Threading.Tasks.Task<WebProyecto.ServicioHoteles.Hotel_cuarto[]> listarCuartosPorHotelAsync(string cod_hotel, System.DateTime fecha_ini, System.DateTime fecha_fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/grabarReservaHotel", ReplyAction="http://tempuri.org/IHoteles/grabarReservaHotelResponse")]
        WebProyecto.ServicioHoteles.Hotel_reserva grabarReservaHotel(WebProyecto.ServicioHoteles.Hotel_reserva nuevaReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/grabarReservaHotel", ReplyAction="http://tempuri.org/IHoteles/grabarReservaHotelResponse")]
        System.Threading.Tasks.Task<WebProyecto.ServicioHoteles.Hotel_reserva> grabarReservaHotelAsync(WebProyecto.ServicioHoteles.Hotel_reserva nuevaReserva);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/ListarDestinoXFiltro", ReplyAction="http://tempuri.org/IHoteles/ListarDestinoXFiltroResponse")]
        WebProyecto.ServicioHoteles.Destino[] ListarDestinoXFiltro(string p_NomDestino);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/ListarDestinoXFiltro", ReplyAction="http://tempuri.org/IHoteles/ListarDestinoXFiltroResponse")]
        System.Threading.Tasks.Task<WebProyecto.ServicioHoteles.Destino[]> ListarDestinoXFiltroAsync(string p_NomDestino);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelesChannel : WebProyecto.ServicioHoteles.IHoteles, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelesClient : System.ServiceModel.ClientBase<WebProyecto.ServicioHoteles.IHoteles>, WebProyecto.ServicioHoteles.IHoteles {
        
        public HotelesClient() {
        }
        
        public HotelesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebProyecto.ServicioHoteles.Hotel[] listarTodosHoteles() {
            return base.Channel.listarTodosHoteles();
        }
        
        public System.Threading.Tasks.Task<WebProyecto.ServicioHoteles.Hotel[]> listarTodosHotelesAsync() {
            return base.Channel.listarTodosHotelesAsync();
        }
        
        public WebProyecto.ServicioHoteles.Hotel[] listarHotelesxHorarios(int dept, int prov, int dist, System.DateTime fecha_ini, System.DateTime fecha_fin) {
            return base.Channel.listarHotelesxHorarios(dept, prov, dist, fecha_ini, fecha_fin);
        }
        
        public System.Threading.Tasks.Task<WebProyecto.ServicioHoteles.Hotel[]> listarHotelesxHorariosAsync(int dept, int prov, int dist, System.DateTime fecha_ini, System.DateTime fecha_fin) {
            return base.Channel.listarHotelesxHorariosAsync(dept, prov, dist, fecha_ini, fecha_fin);
        }
        
        public WebProyecto.ServicioHoteles.Hotel_cuarto[] listarCuartosPorHotel(string cod_hotel, System.DateTime fecha_ini, System.DateTime fecha_fin) {
            return base.Channel.listarCuartosPorHotel(cod_hotel, fecha_ini, fecha_fin);
        }
        
        public System.Threading.Tasks.Task<WebProyecto.ServicioHoteles.Hotel_cuarto[]> listarCuartosPorHotelAsync(string cod_hotel, System.DateTime fecha_ini, System.DateTime fecha_fin) {
            return base.Channel.listarCuartosPorHotelAsync(cod_hotel, fecha_ini, fecha_fin);
        }
        
        public WebProyecto.ServicioHoteles.Hotel_reserva grabarReservaHotel(WebProyecto.ServicioHoteles.Hotel_reserva nuevaReserva) {
            return base.Channel.grabarReservaHotel(nuevaReserva);
        }
        
        public System.Threading.Tasks.Task<WebProyecto.ServicioHoteles.Hotel_reserva> grabarReservaHotelAsync(WebProyecto.ServicioHoteles.Hotel_reserva nuevaReserva) {
            return base.Channel.grabarReservaHotelAsync(nuevaReserva);
        }
        
        public WebProyecto.ServicioHoteles.Destino[] ListarDestinoXFiltro(string p_NomDestino) {
            return base.Channel.ListarDestinoXFiltro(p_NomDestino);
        }
        
        public System.Threading.Tasks.Task<WebProyecto.ServicioHoteles.Destino[]> ListarDestinoXFiltroAsync(string p_NomDestino) {
            return base.Channel.ListarDestinoXFiltroAsync(p_NomDestino);
        }
    }
}
