//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_HotelesTest.HotelesWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCF_HotelesTest.HotelesWS.Hotel_cuarto[] cuartosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int departamanetoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int distritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int provinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_HotelesTest.HotelesWS.Hotel_cuarto[] cuartos {
            get {
                return this.cuartosField;
            }
            set {
                if ((object.ReferenceEquals(this.cuartosField, value) != true)) {
                    this.cuartosField = value;
                    this.RaisePropertyChanged("cuartos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int departamaneto {
            get {
                return this.departamanetoField;
            }
            set {
                if ((this.departamanetoField.Equals(value) != true)) {
                    this.departamanetoField = value;
                    this.RaisePropertyChanged("departamaneto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int distrito {
            get {
                return this.distritoField;
            }
            set {
                if ((this.distritoField.Equals(value) != true)) {
                    this.distritoField = value;
                    this.RaisePropertyChanged("distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int provincia {
            get {
                return this.provinciaField;
            }
            set {
                if ((this.provinciaField.Equals(value) != true)) {
                    this.provinciaField = value;
                    this.RaisePropertyChanged("provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel_cuarto", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hoteles.Dominio")]
    [System.SerializableAttribute()]
    public partial class Hotel_cuarto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int capacidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double costo_nocheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int capacidad {
            get {
                return this.capacidadField;
            }
            set {
                if ((this.capacidadField.Equals(value) != true)) {
                    this.capacidadField = value;
                    this.RaisePropertyChanged("capacidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double costo_noche {
            get {
                return this.costo_nocheField;
            }
            set {
                if ((this.costo_nocheField.Equals(value) != true)) {
                    this.costo_nocheField = value;
                    this.RaisePropertyChanged("costo_noche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numero {
            get {
                return this.numeroField;
            }
            set {
                if ((this.numeroField.Equals(value) != true)) {
                    this.numeroField = value;
                    this.RaisePropertyChanged("numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelesWS.IHoteles")]
    public interface IHoteles {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/listarTodosHoteles", ReplyAction="http://tempuri.org/IHoteles/listarTodosHotelesResponse")]
        WCF_HotelesTest.HotelesWS.Hotel[] listarTodosHoteles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/listarTodosHoteles", ReplyAction="http://tempuri.org/IHoteles/listarTodosHotelesResponse")]
        System.Threading.Tasks.Task<WCF_HotelesTest.HotelesWS.Hotel[]> listarTodosHotelesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/listarHotelesxHorarios", ReplyAction="http://tempuri.org/IHoteles/listarHotelesxHorariosResponse")]
        WCF_HotelesTest.HotelesWS.Hotel[] listarHotelesxHorarios(int dept, int prov, int dist, System.DateTime fecha_ini, System.DateTime fecha_fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/listarHotelesxHorarios", ReplyAction="http://tempuri.org/IHoteles/listarHotelesxHorariosResponse")]
        System.Threading.Tasks.Task<WCF_HotelesTest.HotelesWS.Hotel[]> listarHotelesxHorariosAsync(int dept, int prov, int dist, System.DateTime fecha_ini, System.DateTime fecha_fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/listarCuartosPorHotel", ReplyAction="http://tempuri.org/IHoteles/listarCuartosPorHotelResponse")]
        WCF_HotelesTest.HotelesWS.Hotel_cuarto[] listarCuartosPorHotel(string cod_hotel, System.DateTime fecha_ini, System.DateTime fecha_fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHoteles/listarCuartosPorHotel", ReplyAction="http://tempuri.org/IHoteles/listarCuartosPorHotelResponse")]
        System.Threading.Tasks.Task<WCF_HotelesTest.HotelesWS.Hotel_cuarto[]> listarCuartosPorHotelAsync(string cod_hotel, System.DateTime fecha_ini, System.DateTime fecha_fin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelesChannel : WCF_HotelesTest.HotelesWS.IHoteles, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelesClient : System.ServiceModel.ClientBase<WCF_HotelesTest.HotelesWS.IHoteles>, WCF_HotelesTest.HotelesWS.IHoteles {
        
        public HotelesClient() {
        }
        
        public HotelesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_HotelesTest.HotelesWS.Hotel[] listarTodosHoteles() {
            return base.Channel.listarTodosHoteles();
        }
        
        public System.Threading.Tasks.Task<WCF_HotelesTest.HotelesWS.Hotel[]> listarTodosHotelesAsync() {
            return base.Channel.listarTodosHotelesAsync();
        }
        
        public WCF_HotelesTest.HotelesWS.Hotel[] listarHotelesxHorarios(int dept, int prov, int dist, System.DateTime fecha_ini, System.DateTime fecha_fin) {
            return base.Channel.listarHotelesxHorarios(dept, prov, dist, fecha_ini, fecha_fin);
        }
        
        public System.Threading.Tasks.Task<WCF_HotelesTest.HotelesWS.Hotel[]> listarHotelesxHorariosAsync(int dept, int prov, int dist, System.DateTime fecha_ini, System.DateTime fecha_fin) {
            return base.Channel.listarHotelesxHorariosAsync(dept, prov, dist, fecha_ini, fecha_fin);
        }
        
        public WCF_HotelesTest.HotelesWS.Hotel_cuarto[] listarCuartosPorHotel(string cod_hotel, System.DateTime fecha_ini, System.DateTime fecha_fin) {
            return base.Channel.listarCuartosPorHotel(cod_hotel, fecha_ini, fecha_fin);
        }
        
        public System.Threading.Tasks.Task<WCF_HotelesTest.HotelesWS.Hotel_cuarto[]> listarCuartosPorHotelAsync(string cod_hotel, System.DateTime fecha_ini, System.DateTime fecha_fin) {
            return base.Channel.listarCuartosPorHotelAsync(cod_hotel, fecha_ini, fecha_fin);
        }
    }
}
